### ISSUE TITLE
Add check for non-pointers stored within sync.Pool

### ISSUE THREAD

**Issue by rasky** [dominikh/go-staticcheck#10]
To avoid spurious allocations, sync.Pool should always be used with pointers. For instance, when storing buffers as slices, a pointer to slice should be used instead of the slice itself. This was brought up in http://golang.org/cl/24371

Since the primary goal of sync.Pool is to reduce allocations, I think it might be worth adding a check to staticcheck about this. The check could be triggered on Put() calls in which the argument is not a pointer.

(this was first submitted as a feature request to go vet, but closed as out of scope: https://github.com/golang/go/issues/16311)

**Comment by dominikh** [comment]
This feels a bit out of place in staticcheck. The tool checks for incorrect code, not for performance improvements.

**Comment by bradleyfalzon** [comment]
Other examples found:
- https://github.com/boltdb/bolt/blob/master/tx.go#L536
- https://github.com/anacrolix/torrent/blob/master/torrent.go#L1003
- https://github.com/peco/peco/blob/master/filter.go#L221

**Comment by dominikh** [comment]
Closed by 25dd029e52ecf64171d565c0488fb8b725442398
