### ISSUE TITLE
nil crash in append check

### ISSUE THREAD

**Issue by riking** [dominikh/go-staticcheck#18]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x73b09]

goroutine 1 [running]:
panic(0x42ef20, 0xc4200140a0)
	goroot/src/runtime/panic.go:500 +0x1a1
honnef.co/go/staticcheck.CheckIneffectiveAppend.func1(0x1a65180, 0xc4201dab40, 0xc4201de101)
	go/src/honnef.co/go/staticcheck/lint.go:1820 +0x3c9
```

`ssafn.ValueForExpr(call)` does not always return an expression, and I hit this case in my code.

Unfortunately, the file is 1k LOC so I don't have a minimized example. But I changed the code to make an error when the expr is nil, and here's one of the matched lines:

```
	var newEmojiAry []ReplyActionEmoji
	newEmoji := mod.GetEmojiForResponse(result)
/* ! */	newEmojiAry = append(newEmojiAry, ReplyActionEmoji{MessageID: fciMeta.OriginalMsg.MessageID(), Emoji: newEmoji})
/* ! */	newEmojiAry = append(newEmojiAry, ReplyActionEmoji{MessageID: fciMeta.OriginalMsg.MessageID(), Emoji: "fast_forward"})
	fciMeta.ChangeEmoji(mod, newEmojiAry)
```

If I change the code to skip `if !ok`, it flags a similar pattern under the SA4006 check.

**Comment by dominikh** [comment]
> If I change the code to skip if !ok, it flags a similar pattern under the SA4006 check

Which `if !ok` are you referring to? Also, are you sure that the result of `ssafn.ValueForExpr(call)` is nil, and not `expr.Referrers()` on the following line?

**Comment by riking** [comment]
I changed `expr, _ = ssafn.ValueForExpr()` to `expr, ok :=
ssafn.ValueForExpr(); if !ok {return true}` and it stopped crashing.
Clearly because expr is nil when ok is false.

And yes, it was the usage of expr that was crashing, not the ssafn method
call - the ssafn call was returning nil (as its documentation states).

On Wed, Nov 16, 2016, 11:34 PM Dominik Honnef notifications@github.com
wrote:

If I change the code to skip if !ok, it flags a similar pattern under the
SA4006 check

Which if !ok are you referring to? Also, are you sure that the result of
ssafn.ValueForExpr(call) is nil, and not expr.Referrers() on the following
line?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/dominikh/go-staticcheck/issues/18#issuecomment-261175827,
or mute the thread

**Comment by dominikh** [comment]
The second value returned by ValueForExpr isn't an `ok` bool, it reports whether the returned value is an address or not. It being false is no indication of expr being nil. Can you explicitly check that expr is nil, or provide a self-contained example with which I can reproduce the issue? If the code base is public it's fine to just link me to that.

**Comment by riking** [comment]
Right, I could do that. Whoops.

https://github.com/riking/homeapi/tree/master/marvin/modules/atcommand

Was avoiding posting that because I was actively editing it and wasn't sure if I would delete the repro, but didn't touch that part much.

**Comment by dominikh** [comment]
`expr` was nil due to dead code elimination performed by `go/ssa`.
