### ISSUE TITLE
Detect leaky use of time.Tick

### ISSUE THREAD

**Issue by bradleyfalzon** [dominikh/go-staticcheck#20]
https://golang.org/pkg/time/#Tick is appropriate in some cases, but will leak a goroutine as it doesn't provide a mechanism to close the routine. To prevent leaks, it's recommended to use https://golang.org/pkg/time/#NewTicker and close the ticker when no longer required.

As discussed, simply detecting the use time `time.Tick` will result in false positives, to help reduce them (and also create some false negatives):

- Ignore the use of `time.Tick` in main packages (i.e. not libraries), as short running cli applications may not care about leaking goroutines
- Ignore functions that call `time.Tick` and never return, to prevent valid use of infinite loops such as a `for { select { case <-tick: } }` block.

**Comment by dominikh** [comment]
> Ignore the use of time.Tick in libraries (non-main packages), as short running cli applications may not care about leaking goroutines

Surely you mean ignore them only in main packages? If we ignore them in libraries, there won't be much left to flag, and all the ones in main are probably false positives.

**Comment by bradleyfalzon** [comment]
Yes, edited, thanks.

**Comment by dominikh** [comment]
Update: I have this implemented locally, but it's blocking on some other yet unpushed changes.
