### ISSUE TITLE
SA4005 - is a pointer OK

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-staticcheck#27]
Take this code from https://github.com/ziutek/mymysql:

```go
func (tr Transaction) Commit() error {
	_, err := tr.Start("COMMIT")
	tr.Conn = nil // Invalidate this transaction
	return err
}
```

`tr.Conn` here gets flagged as "ineffective assignment to field Conn". Is that true though if Conn is a pointer? Here's the struct definition:

```go
type Transaction struct {
	*Conn
}
```

**Comment by dominikh** [comment]
The type of the field doesn't matter here, what matters is the type of `tr`, which is `Transaction`, a value receiver. Assigning to the field has no observable effect. After `Commit` returns, `tr` will be discarded.

To expand: In the call `tr.Commit()`, the receiver will be a copy of `tr`. Your code has identical behaviour to this code: https://play.golang.org/p/guVv5W90Jw

**Comment by kevinburke** [comment]
Sorry - isn't this more analogous? where X is a pointer. https://play.golang.org/p/TP4ETwuYXV

**Comment by dominikh** [comment]
No, it is analogous to https://play.golang.org/p/AAoedh5ntY – your code is not dereferencing a pointer, it's assigning to a field.

**Comment by kevinburke** [comment]
Thanks for clarifying!
