### ISSUE TITLE
Be added to gometalinter

### ISSUE THREAD

**Issue by santagada** [dominikh/go-staticcheck#38]
https://github.com/alecthomas/gometalinter already groups a ton of static check tools and go-staticcheck could be a interesting addition to it.

**Comment by dominikh** [comment]
Agreed. That's why it was added back in April: https://github.com/alecthomas/gometalinter/commit/31653ad9ac0769bf9f6cf0c2e142c77d59e89316 ;-)

Going to close this issue. Let me know if they dropped me from gometalinter without me knowing!

**Comment by santagada** [comment]
Great I'm using it already then :). So maybe instead of adding it to metalinter, why not add to the readme that it is already on gometalinter?

**Comment by dmitshur** [comment]
Isn't it already there?

https://github.com/alecthomas/gometalinter#supported-linters

**Comment by dominikh** [comment]
In case the suggestion was to add a note to *our* README: I'd rather not. It's not our job to track all the possible tools and "meta linters" that make use of staticcheck; at this point, this tool is popular enough that it's the responsibility of others to support us, not the other way around.
