### ISSUE TITLE
staticcheck -h still runs the linter

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-staticcheck#50]
```
 $ time staticcheck -h
[help stuff]
real    0m0.800s
user    0m1.973s
sys     0m0.100s
```

This is on master as of writing for staticcheck and all of its deps. Running on go tip too if that is at all relevant.

**Comment by dominikh** [comment]
Fixed in https://github.com/dominikh/go-lint/commit/0d04e3c683eb052bf18d889331e846989da97021
