### ISSUE TITLE
Detect 0775, 0755, 0664, 0644 os.FileModes 

### ISSUE THREAD

**Issue by bradleyfalzon** [dominikh/go-staticcheck#52]
Someone may use 0775, 0755, 0664, 0644 as the file mode to `os.OpenFile` (and other functions) intending for this to be the final permissions, but the permission provided should be the maximum permission allowing the caller's umask to restrict this permission further.

This often results in applications using permissions such as 0644 which forbids group write permission, but some users may want groups to have write permission.

I'm really on the fence on this, and happy to not include this check due the likely hood of false positives, but there's a lot of projects calling `os.OpenFile` with permissions that are most likely misunderstood and being overly restrictive. Perhaps just check for 0644 and 0755 and/or marking as dubious?

Related to #51

**Comment by bradleyfalzon** [comment]
I'm concerned some use cases, such as logging, it'd be reasonable to always specify 0644, it's unlikely you would want multiple users writing to the log file, but if the application just called os.Create that's what they would get (given a umask 0002).

**Comment by dominikh** [comment]
I don't think we can flag anything here without immediately running into false positives. We can't tell if 0644 is "overly restrictive", or if it's the maximum permissions that the file should have based on what it is used for.

**Comment by bradleyfalzon** [comment]
I'll close it due to the high chance of false positives and no reliable way to know for certain.
