### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-staticcheck#55]
VRP has a noticeable impact on performance (as is to be expected, it's doing more work). The current implementation is mostly unoptimized.

One easy optimization we can make is building graphs for functions in parallel – right now, they're built sequentially even though there are no dependencies between the graphs.

/cc @tamird

**Comment by tamird** [comment]
At a glance, I noticed there are a bunch of places that appear to care about performance (i.e. slices are preallocated to the correct length) but would be better served by the use of sets.

**Comment by dominikh** [comment]
Some preliminary stats, based on my Intel i7-2600k and the cockroachdb repo:

- Linting packages in parallel reduces the runtime from 22s to 17s
- Running checks, not packages, in parallel behaves similarly but would require larger code changes
- Building VRP graphs in parallel has no appreciable benefit. Most graphs build fast enough to make scheduling overhead noticeable, and there aren't enough pathological cases to benefit from processing those in parallel. For example, in cockroachdb, only the yacc parser is a pathological case requiring seconds to build the graph.

Processing packages in parallel is a simple code change in the `lint` repo, so we'll likely merge that in the coming days. Also, based on the fact that constructing VRP graphs is already very fast for most packages, optimizing it doesn't take priority. If there are simple fixes that hugely benefit the pathological case, however, they should be applied.

About the checks themselves: Given the cockroachdb repo, checks that don't rely on SSA complete in about 100ms combined, whereas those relying on SSA complete in about 500-700ms combined. This does mean that adding new checks has an appreciable cost. Some of these checks probably have some potential for optimization, but there's probably a baseline around the 500ms mark simply for iterating over all the instructions in all the functions.

To put things into perspective, however: According to `cloc`, there are 264,949 lines of Go code in `github.com/cockroachdb/cockroach/pkg/...` – A similar, enterprise-level tool for C# code takes 8-10 minutes for 100k lines of code on comparable, if not better, hardware. Furthermore, the Go stdlib supposedly has 750,263 lines of Go code, which staticcheck processes in 15 seconds, suggesting that cockroachdb is a bit of a pathological case (and indeed, the yacc parser for SQL in cockroachdb takes 5 seconds to process because of its atypical structure and complexity). We're really not doing that bad.

**Comment by tamird** [comment]
Upgrading https://github.com/dominikh/go-staticcheck/compare/866016499c1224a2f7f52e783b44ca72a51fa46c...9f575d2374dfeb3f8da0dd1d8311567cba368fa1 resulted in another substantial performance degradation against https://github.com/cockroachdb/cockroach (via our Metacheck):

Before: 39.036s
After: 54.028s

**Comment by dominikh** [comment]
While regrettable, this degradation in performance is somewhat expected. I'm sure things can be optimized to reduce the impact, but a new feature requires a more extensive model; and a change in the infrastructure requires more indirect calls (interfaces), also slowing things down.

Overall, the performance changes of that range of commits look like this:

![graph](https://cloud.githubusercontent.com/assets/39825/21171411/46747216-c1cc-11e6-92fa-dcf3493c3240.png)

The huge increase were new features, which were afterwards optimized.

**Comment by dominikh** [comment]
The same data in tabular form with more precision: 

| Revision | Wall time (seconds) |
|----------|--------------------- |
| 7ff26e22 |               18.30 |
| 4b71fa66 |               18.82 |
| 152046ec |               19.96 |
| 6358a41d |               19.42 |
| 4484396c |               18.70 |
| 0ea8279f |               18.39 |
| 1ed90c8e |               18.64 |
| c6433216 |               38.40 |
| fb48acf6 |               36.17 |
| e05ec934 |               38.30 |
| 52fd9075 |               70.24 |
| a510d8ba |               70.20 |
| ea839bc2 |               71.34 |
| e4c1feb5 |               66.42 |
| 00f59e9a |               67.92 |
| 80511060 |               31.26 |
| 9add0cb0 |               26.68 |
| 3cf2a651 |               26.07 |
| 9f575d23 |               26.68 |

**Comment by dominikh** [comment]
Another interesting data point is that staticcheck seems to vastly under-utilize multi-core systems, only managing to saturate around 2–2.5 CPU cores. It performs particularly poorly on NUMA systems.

I'll have to check how much of that is due to issues in go/types and go/ssa (these packages are designed to be highly concurrent, but there's no indication of how well it behaves on multi-CPU systems). There is also at least one candidate of poor locking in the linter infrastructure itself. Fixing these issues should give us a decent speed boost.

**Comment by dominikh** [comment]
Latest benchmarks:

![graph](https://cloud.githubusercontent.com/assets/39825/21310091/35fc1cfe-c5e1-11e6-9cb3-ec571d2fb252.png)

@tamird You may want to give a1dced9 a try. It has some minor improvements for single core performance, and some larger improvements for multi core performance. E.g. on my 4 core/8 thread machine, testing the standard library is back to its base line.

**Comment by dominikh** [comment]
Also make sure to update the `lint` dependency to f0b0056. Apparently I forgot to push that 2 weeks ago, which explains some of the discrepancies between my and your results...

**Comment by tamird** [comment]
Good stuff, this got us from 57s to 37s.

**Comment by dominikh** [comment]
https://github.com/dominikh/go-staticcheck/compare/perf drops the runtime for cockroachdb on my machine from 22.09s to 17.42s (
![graph](https://cloud.githubusercontent.com/assets/39825/21332007/fe617f7c-c645-11e6-858d-56bfef6b12f2.png)
)

Running the changes against my corpus to check for crashes, then going to merge them into master tomorrow.

**Edit:** The changes are merged now.

**Comment by tamird** [comment]
These changes bring the runtime further down to 33s, but produce a few new errors:
```
make check TESTS=Meta
go test ./build -v -tags 'check' -run 'TestStyle/Meta'
=== RUN   TestStyle
=== RUN   TestStyle/TestMetacheck
--- FAIL: TestStyle (0.00s)
    --- FAIL: TestStyle/TestMetacheck (32.80s)
    	style_test.go:694: /Users/tamird/src/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/engine_test.go:83:3: the goroutine calls T.Fatal, which must be called in the same goroutine as the test (SA2002)
    	style_test.go:694: /Users/tamird/src/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/engine_test.go:83:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
    	style_test.go:694: -: columnQualification is a pure function but its return value is ignored (SA4017)
    	style_test.go:694: -: namePart is a pure function but its return value is ignored (SA4017)
    	style_test.go:694: -: operator is a pure function but its return value is ignored (SA4017)
    	style_test.go:694: -: operator is a pure function but its return value is ignored (SA4017)
    	style_test.go:694: -: operator is a pure function but its return value is ignored (SA4017)
FAIL
exit status 1
FAIL	github.com/cockroachdb/cockroach/build	32.810s
make: *** [check] Error 1
```

The `SA2002`s are legit (though I don't understand why they are reported now but not earlier), but the `SA4017`s seem overly aggressive:
 - `columnQualification` is part of a "marker" interface, and is never called. https://github.com/cockroachdb/cockroach/blob/001bfa0/pkg/sql/parser/create.go#L372
 - `namePart`: ditto. https://github.com/cockroachdb/cockroach/blob/001bfa0/pkg/sql/parser/name_part.go#L152
 - `operator`: ditto. https://github.com/cockroachdb/cockroach/blob/001bfa0/pkg/sql/parser/expr.go#L92

Note that `SA4017` doesn't report a source location, and also note that there are many other such "marker" interfaces in CRDB that are not reported by this changed logic.

**Comment by dominikh** [comment]
SA2002 is likely matching now because we're checking more functions. We didn't always check closures (due to a bug). 

I will look into SA4017 – missing source positions are a good indication of a bug

**Comment by dominikh** [comment]
SA4017 was #66 and is now fixed.

**Comment by dominikh** [comment]
I'm going to close this issue. Performance is (IMHO) acceptable now, and any future regressions should be filed as new issues.
