### ISSUE TITLE
request: allow *callsites* to opt-out of certain rules

### ISSUE THREAD

**Issue by dt** [dominikh/go-staticcheck#58]
My use case is that i'm maintaining a proxying wrapper implementation of an upstream interface. Upstream deprecated a few methods in that interface, which I've also deprecated in my wrapper, but to maintain interface compatibility, I want to keep the proxying calls.

Obviously I could pass a `-ignore` for each of these, but ideally I'd like to indicate _at the callsite_ that I want the warning about the upstream deprecation ignored, rather than expecting everyone running staticcheck to pass the ignore every time.

**Comment by dominikh** [comment]
We will not introduce a mechanism for suppressing rules in source files.

What could make sense here is to not emit the deprecation warning if the call occurs in a function that itself is deprecated. Would that work for you?
