### ISSUE TITLE
os.Exit(0) should be a return in main()

### ISSUE THREAD

**Issue by mvdan** [dominikh/go-staticcheck#59]
I'm not sure if this should go in go-simple or here, so feel free to move.

Although I think these two are equivalent, surely the second is simpler and preferred in every case:

```
func main() {
    if foo {
        bar()
        os.Exit(0)
    }
    etc()
}
```

```
func main() {
    if foo {
        bar()
        return
    }
    etc()
}
```

**Comment by dominikh** [comment]
I find that to be controversial. When you're already using os.Exit for non-zero exit, it seems more consistent to use os.Exit for the zero case, too. Admittedly, if os.Exit(0) is the only use of os.Exit, return *might* be simpler; or it could be used to be consistent with other commands or code in other files.

I don't think that making a suggestion here, in whatever form, benefits the code base enough. It is hardly any simpler code, and there are too many reasons for using the original form.

**Comment by dominikh** [comment]
(Also yes, this would've went into gosimple, not staticcheck.)

**Comment by mvdan** [comment]
Fair enough. Thanks!
