### ISSUE TITLE
(suggestion) check filepath.Walk misusage

### ISSUE THREAD

**Issue by AkihiroSuda** [dominikh/go-staticcheck#6]
https://golang.org/pkg/path/filepath/#Walk

``` go
func Walk(root string, walkFn WalkFunc) error
type WalkFunc func(path string, info os.FileInfo, err error) error
```

Sometimes people ignore `err` in their own `WalkFunc`.
real-world example: https://github.com/docker/docker/issues/23004

So I suggest checking whether `err` is ignored in `WalkFunc`.

I can work on this if I can get positive feedback.

**Comment by dmitshur** [comment]
Is this not a problem that [`errcheck`](https://github.com/kisielk/errcheck) would detect already?

**Comment by AkihiroSuda** [comment]
In my understanding `errcheck` cannot detect unchecked errors in _arguments_ (not in returned value).

``` go
package main

import (
        "os"
        "path/filepath"
)

func main() {
        err := filepath.Walk("/dummy", func(d string, fileInfo os.FileInfo, e error) error {
                return nil // ignore e
        })
        if err != nil {
                panic(err)
        }
}
```

```
$ go get -u github.com/kisielk/errcheck
$ errcheck a.go
(empty result)
```

Should I make a suggestion to errcheck community rather than staticcheck?

**Comment by dgryski** [comment]
I think errcheck to be fixed to handle this.

**Comment by dominikh** [comment]
Do propose the check to the errcheck dev first please. I'm happy to add this to staticcheck if he rejects the idea.

**Comment by AkihiroSuda** [comment]
OK, thank you all!
