### ISSUE TITLE
Ticker not stopped

### ISSUE THREAD

**Issue by judwhite** [dominikh/go-staticcheck#68]
If possible to determine if the ticker / ticker chan doesn't escape the local method (or closure) it should be stopped.

Somewhat interestingly [time.Tick](https://golang.org/pkg/time/#Tick) intentionally allows the ticker to leak for convenience.

**Comment by bradleyfalzon** [comment]
Is this a duplicate of SA1015? Or extension of?

**Comment by dominikh** [comment]
They're related. One SA1015 is about use of time.Tick, whereas this would be about an actually stoppable ticker that wasn't stopped.
