### ISSUE TITLE
Checks equivalent to Aspirator

### ISSUE THREAD

**Issue by doherty** [dominikh/go-staticcheck#70]
The 2014 paper [*Simple Testing Can Prevent Most Critical Failures: An Analysis of Production Failures in Distributed Data-Intensive Systems*](https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-yuan.pdf) suggests a number of checks similar to what staticcheck already does. The authors implemented a system called Aspirator to check some of the simple cases in Java code, such as if error-handling code has "TODO" or "FIXME" comments; if it is empty; or if it has only a logging statement. It'd be great if we could bring these into staticcheck.

**Comment by dominikh** [comment]
I haven't read the paper yet, so take my opinions with a grain of salt. I'm not sure how well those checks would fit into staticcheck, from a user experience point of view. Staticcheck is in this odd position where people use it both in their editors while writing new code, and "offline" on large corpora. In the former context, complaining loudly about TODOs could be perceived as rather annoying and not very helpful. On the other hand, if there are enough checks of that kind, we could create a whole new category for them that would be easy to enable/ignore as needed. Something akin to a "this code isn't production ready" category, maybe.

Those complications aside, I'll definitely take a look at the paper and the proposed checks once I get the chance.
