### ISSUE TITLE
Ignoring instances of SA4006

### ISSUE THREAD

**Issue by nicksnyder** [dominikh/go-staticcheck#73]
I have some code that looks like this:

```go
func DoSomething(ctx context.Context) {
    ctx, done := trace(ctx, "ThisPackageName", "DoSomething")
    defer done()

    // the rest of the code
    otherpackage.DoSomethingElse(ctx)
}
```

For all functions we create a new trace context to keep track of the call stack. This is fine as long as the function actually uses ctx, but if it doesn't, then we see `this value of ctx is never used (SA4006)`. Ideally we always want to put the trace line there and assign it to ctx so that any future usages of ctx use the correct one.

We don't want to ignore SA4006 for whole files because it is useful and has caught unhandled errors (thanks!).

I tried adding `_ = ctx` but staticcheck doesn't treat this as a usage. Is there any way to suppress this check for a specific variable instead of a whole file?

**Comment by dominikh** [comment]
We should probably suppress the warnings for variables assigned to the blank identifier. I don't have a timeline for this, but I'll try to evaluate, and possibly get it done, this week.

In the meantime, there isn't really an alternative to ignoring whole files or actually using the variable. A quick hack would be to declare a function that accepts the context as an argument and does nothing with it. I'm not sure how acceptable that would be to you (it is rather gross IMO). If it is acceptable to you, you could later deprecate that function, and have SA1019 tell you all the places where it's being used.

**Comment by testnicksnyder** [comment]
Thanks for taking a look! Yeah I think `_ = ctx` would be ideal. For now we are just removing the assignment to ctx to workaround and leave the responsibility with the future dev.
